export const SECTION_EMOJIS = {
  institutions: "🏛️",
  "architectural-projects": "🏗️",
  "niani-tv": "📺",
  nianiCartoons: "🎬",
  nianiWomen: "👑",
  nko: "📖",
  "history-courses": "📜",
  others: "🎓",
  federation: "🗺️",
  organization: "👑",
  affiliation: "🤝",
  join: "🎯",
  questions: "🙋🏿‍♂️❓",
  entrepreneur: "👧🏿🛍️",
  cotiser: "🪙",
  commerce: "🛍️",
  economy: "💰",
  introduction: "👋",
  history: "📜",
  governance: "⚖️",
  culture: "🎭",
  resources: "📚",
  overview: "🌐",
  wantToJoin: "🎯",
  haveQuestions: "🙋🏿‍♂️❓",
  coursesNko: "📖",
  historyCourses: "📜",
  otherCourses: "🎓",
  connection: "🔑",
  byCountry: "🗺️",
  byOrganization: "👑",
  byAffiliation: "🤝",
  globalPerspectives: "🌍",
  referenceBureau: "📋",
  niani: "🏰",
  academy: "🎓",
  sanunJara: "🦁",
  manden: "🌍",
  vision: "✨",
  mission: "🎯",
  fundamentalValues: "📖",
  merchants: "🏪",
  suppliers: "📦",
  contactDirectory: "📞",
  login: "🔑",
  membership: "👤",
  recommendation: "🤝",
  admin: "🛡️",
  historyTimeline: "⏳",
  historyScroll: "📜",
  emptyVideos: "🎥",
  emptyCartoons: "🎬",
  FileText: "📄",
  Globe: "🌍",
  LayoutDashboard: "📊",
  Clock: "🕐",
  Crown: "👑",
  DollarSign: "💵",
  Building2: "🏢",
  Users: "👥",
  BookOpen: "📖",
  FolderOpen: "📁",
  Layers: "📚",
} as const;

export type SectionEmojiKey = keyof typeof SECTION_EMOJIS;

export function sectionEmoji(key: string): string {
  return SECTION_EMOJIS[key as SectionEmojiKey] ?? "✨";
}
